### ISSUE TITLE
error while running face_recog_eigen.py 

### ISSUE THREAD

**Issue by priyablue** [tanay-bits/cvlib#1]
OpenCV Error: Unspecified error (File can't be opened for writing!) in load, file /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/contrib/src/facerec.cpp, line 325
Traceback (most recent call last):
  File "face_recog_eigen.py", line 76, in <module>
    recognizer.load_trained_data()
  File "face_recog_eigen.py", line 24, in load_trained_data
    self.model.load('eigen_trained_data.xml')
cv2.error: /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/contrib/src/facerec.cpp:325: error: (-2) File can't be opened for writing! in function load

why is this error 
help me out to sort it out

**Comment by priyablue** [comment]
will it be automatically generate the xml file or we need to create it with the trained face_train_eigen.py /face_train_fisher.py 

Could you make me clear of this doubt
